// Mock data for testing without database connection

export const mockUser = {
  id: 1,
  email: "demo@example.com",
  name: "Demo User",
  avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=demo",
};

export const mockPreferences = {
  id: 1,
  userId: 1,
  employmentTypes: ["Full-time", "Contract"],
  workMode: "remote",
  location: "San Francisco, CA",
  createdAt: new Date(),
  updatedAt: new Date(),
};

export const mockJobs = [
  {
    id: 1,
    userId: 1,
    company: "Google",
    companyId: "google",
    companyLogo: "https://logo.clearbit.com/google.com",
    position: "Senior Software Engineer",
    location: "Mountain View, CA",
    postedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000), // 2 days ago
    matchPercentage: 92,
    salaryMin: "150000",
    salaryMax: "200000",
    jobType: "Full-time",
    workType: "hybrid",
    experienceLevel: "Senior",
    description: "Join Google's engineering team to build products that impact billions of users worldwide. We're looking for experienced engineers passionate about scalable systems.",
    linkedinJobId: "mock-job-1",
    linkedinUrl: "https://www.linkedin.com/jobs/view/mock-job-1",
    applyUrl: "https://careers.google.com/apply",
    source: "linkedin",
    scrapedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: 2,
    userId: 1,
    company: "Meta",
    companyId: "meta",
    companyLogo: "https://logo.clearbit.com/meta.com",
    position: "Full Stack Engineer",
    location: "Menlo Park, CA",
    postedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000), // 5 days ago
    matchPercentage: 88,
    salaryMin: "140000",
    salaryMax: "190000",
    jobType: "Full-time",
    workType: "onsite",
    experienceLevel: "Mid-Senior",
    description: "Build the future of social technology at Meta. Work on cutting-edge projects in React, Node.js, and distributed systems.",
    linkedinJobId: "mock-job-2",
    linkedinUrl: "https://www.linkedin.com/jobs/view/mock-job-2",
    applyUrl: "https://www.metacareers.com/apply",
    source: "linkedin",
    scrapedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: 3,
    userId: 1,
    company: "Amazon",
    companyId: "amazon",
    companyLogo: "https://logo.clearbit.com/amazon.com",
    position: "Software Development Engineer",
    location: "Seattle, WA",
    postedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000), // 7 days ago
    matchPercentage: 85,
    salaryMin: "130000",
    salaryMax: "180000",
    jobType: "Full-time",
    workType: "hybrid",
    experienceLevel: "Mid-Level",
    description: "Amazon is seeking talented software engineers to join our team. Work on high-impact projects that serve millions of customers.",
    linkedinJobId: "mock-job-3",
    linkedinUrl: "https://www.linkedin.com/jobs/view/mock-job-3",
    applyUrl: "https://www.amazon.jobs/apply",
    source: "linkedin",
    scrapedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: 4,
    userId: 1,
    company: "Microsoft",
    companyId: "microsoft",
    companyLogo: "https://logo.clearbit.com/microsoft.com",
    position: "Software Engineer II",
    location: "Redmond, WA",
    postedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000), // 10 days ago
    matchPercentage: 90,
    salaryMin: "135000",
    salaryMax: "185000",
    jobType: "Full-time",
    workType: "remote",
    experienceLevel: "Mid-Level",
    description: "Join Microsoft to empower every person and organization on the planet to achieve more. Work with Azure, AI, and cloud technologies.",
    linkedinJobId: "mock-job-4",
    linkedinUrl: "https://www.linkedin.com/jobs/view/mock-job-4",
    applyUrl: "https://careers.microsoft.com/apply",
    source: "linkedin",
    scrapedAt: new Date(),
    createdAt: new Date(),
  },
  {
    id: 5,
    userId: 1,
    company: "Apple",
    companyId: "apple",
    companyLogo: "https://logo.clearbit.com/apple.com",
    position: "Software Engineer - iOS",
    location: "Cupertino, CA",
    postedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000), // 14 days ago
    matchPercentage: 87,
    salaryMin: "145000",
    salaryMax: "195000",
    jobType: "Full-time",
    workType: "onsite",
    experienceLevel: "Mid-Senior",
    description: "Apple is looking for passionate engineers to build the next generation of iOS applications. Work on products used by millions worldwide.",
    linkedinJobId: "mock-job-5",
    linkedinUrl: "https://www.linkedin.com/jobs/view/mock-job-5",
    applyUrl: "https://jobs.apple.com/apply",
    source: "linkedin",
    scrapedAt: new Date(),
    createdAt: new Date(),
  },
];

export const mockInterviews = [
  {
    id: 1,
    userId: 1,
    company: "Google",
    position: "Senior Software Engineer",
    interviewDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000), // 7 days from now
    status: "scheduled",
    notes: "Technical interview with the team lead. Focus on system design and algorithms.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    userId: 1,
    company: "Meta",
    position: "Full Stack Engineer",
    interviewDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000), // 3 days ago
    status: "completed",
    notes: "Behavioral interview went well. Discussed past projects and team collaboration.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const mockMockSessions = [
  {
    id: 1,
    userId: 1,
    topic: "System Design",
    difficulty: "hard",
    targetPosition: "Senior Software Engineer",
    status: "completed",
    score: 85,
    feedback: "Good understanding of distributed systems. Could improve on load balancing strategies.",
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: 2,
    userId: 1,
    topic: "Behavioral",
    difficulty: "medium",
    targetPosition: "Software Engineer",
    status: "in_progress",
    score: null,
    feedback: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const mockMockMessages = [
  {
    id: 1,
    sessionId: 1,
    role: "assistant",
    content: "Let's start with a system design question. Design a URL shortening service like bit.ly. What are the key components you would consider?",
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: 2,
    sessionId: 1,
    role: "user",
    content: "I would start by identifying the functional requirements: creating short URLs, redirecting to original URLs, and analytics. For the system design, I'd use a hash function for URL generation, a database for storage, and a cache layer for performance.",
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 60000),
  },
  {
    id: 3,
    sessionId: 1,
    role: "assistant",
    content: "Great start! Can you elaborate on the database choice and how you would handle high traffic scenarios?",
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 120000),
  },
];

export const mockBookmarks = [
  {
    id: 1,
    userId: 1,
    topic: "Algorithms",
    question: "Implement a function to reverse a linked list",
    difficulty: "medium",
    targetPosition: "Software Engineer",
    notes: "Remember to handle edge cases like empty list and single node",
    category: "Data Structures",
    practiceCount: 3,
    lastPracticedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: 2,
    userId: 1,
    topic: "System Design",
    question: "Design a rate limiter",
    difficulty: "hard",
    targetPosition: "Senior Software Engineer",
    notes: "Consider token bucket vs sliding window algorithms",
    category: "System Design",
    practiceCount: 1,
    lastPracticedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
  },
];

export const mockAssessmentReports = [
  {
    id: 1,
    sessionId: 1,
    userId: 1,
    overallScore: 85,
    technicalScore: 88,
    communicationScore: 82,
    problemSolvingScore: 86,
    strengths: ["Strong understanding of distributed systems", "Clear communication", "Good problem decomposition"],
    weaknesses: ["Could improve on load balancing strategies", "Need more practice with edge cases"],
    recommendations: ["Study consistent hashing algorithms", "Practice more system design problems"],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
];

export const mockKnowledgeBases = [
  {
    id: 1,
    userId: 1,
    name: "System Design Fundamentals",
    description: "Key concepts for system design interviews",
    content: "Topics include: scalability, load balancing, caching, database sharding, CAP theorem",
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
  },
];

export const mockJobTrackerItems = [
  {
    id: 1,
    userId: 1,
    company: "Google",
    position: "Senior Software Engineer",
    status: "interviewing",
    appliedDate: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
    notes: "Passed phone screen, scheduled for onsite",
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: 2,
    userId: 1,
    company: "Meta",
    position: "Full Stack Engineer",
    status: "applied",
    appliedDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    notes: "Waiting for response",
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
  },
];
